# Build customization
builds:
  - main: .
    binary: tsprofiler-bwnetflow
    goos:
      - linux
    goarch:
      - amd64

nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  vendor: Christopher B. Hauser
  homepage: https://cha87de.github.io/tsprofiler-bwnetflow/
  maintainer: Christopher B. Hauser <post@c-ha.de>
  description: integration of tsprofiler into bwnetflow network analysis toolkit
  license: GPL-3.0

  # Formats to be generated.
  formats:
    - deb
    - rpm

  # Override default /usr/local/bin destination for binaries
  bindir: /usr/bin